export const companyArray = [
  {
    sheetName: '$META',
    companyName: 'Meta',
    revenueQuarter: 1,
    revenueRow: 5,
    netIncomeRow: 27,
    grossMarginRow: 11,
    icon: require('@/assets/icons/meta.svg'),
    color: '#39DAFF',
  },
  {
    sheetName: '$TSLA',
    companyName: 'Tesla',
    revenueQuarter: 1,
    revenueRow: 13,
    netIncomeRow: 44,
    grossMarginRow: 26,
    icon: require('@/assets/icons/tesla.svg'),
    color: '#31BFE2',
  },
  {
    sheetName: '$NVDA',
    companyName: 'Nvidia',
    revenueQuarter: 1,
    revenueRow: 5,
    netIncomeRow: 29,
    grossMarginRow: 11,
    icon: require('@/assets/icons/nvidia.svg'),
    color: '#29A5C5',
  },
  {
    sheetName: '$MSFT',
    companyName: 'Microsoft',
    revenueQuarter: 1,
    revenueRow: 9,
    netIncomeRow: 30,
    grossMarginRow: 15,
    icon: require('@/assets/icons/microsoft.svg'),
    color: '#218AA8',
  },
  {
    sheetName: '$AAPL',
    companyName: 'Apple',
    revenueQuarter: 1,
    revenueRow: 3,
    netIncomeRow: 36,
    grossMarginRow: 23,
    icon: require('@/assets/icons/apple.svg'),
    color: '#196F8C',
  },
  {
    sheetName: '$GOOG',
    companyName: 'Google',
    revenueQuarter: 1,
    revenueRow: 5,
    netIncomeRow: 41,
    grossMarginRow: 25,
    icon: require('@/assets/icons/google.svg'),
    color: '#11546F',
  },
  {
    sheetName: '$AMZN',
    companyName: 'Amazon',
    revenueQuarter: 1,
    revenueRow: 9,
    netIncomeRow: 41,
    grossMarginRow: 15,
    icon: require('@/assets/icons/amazon.svg'),
    color: '#093A52',
  },
];
