export const globalArray = [
  {
    sheetName: '$APPL',
    companyName: 'Apple',
    revenueRow: 5,
    netIncomeRow: 36,
    grossMarginRow: 23,
    icon: './assets/icons/apple.svg',
  },
  {
    sheetName: '$AMZN',
    companyName: 'Amazon',
    revenueRow: 9,
    netIncomeRow: 41,
    grossMarginRow: 15,
    icon: './assets/icons/amazon.svg',
  },
  {
    sheetName: '$GOOG',
    companyName: 'Google',
    revenueRow: 5,
    netIncomeRow: 41,
    grossMarginRow: 25,
    icon: './assets/icons/google.svg',
  },
  {
    sheetName: '$META',
    companyName: 'Meta',
    revenueRow: 5,
    netIncomeRow: 27,
    grossMarginRow: 11,
    icon: './assets/icons/meta.svg',
  },
  {
    sheetName: '$MSFT',
    companyName: 'Microsoft',
    revenueRow: 9,
    netIncomeRow: 30,
    grossMarginRow: 15,
    icon: './assets/icons/microsoft.svg',
  },
  {
    sheetName: '$NVDA',
    companyName: 'Nvidia',
    revenueRow: 5,
    netIncomeRow: 29,
    grossMarginRow: 11,
    icon: './assets/icons/nvidia.svg',
  },
  {
    sheetName: '$TSLA',
    companyName: 'Tesla',
    revenueRow: 13,
    netIncomeRow: 44,
    grossMarginRow: 26,
    icon: './assets/icons/tesla.svg',
  }
];