export const globalArray = [
  {
    sheetName: '$AAPL',
    companyName: 'Apple',
    revenueQuarter: 1,
    revenueRow: 3,
    netIncomeRow: 36,
    grossMarginRow: 23,
    icon: require('@/assets/icons/apple.svg'),
  },
  {
    sheetName: '$AMZN',
    companyName: 'Amazon',
    revenueQuarter: 1,
    revenueRow: 9,
    netIncomeRow: 41,
    grossMarginRow: 15,
    icon: require('@/assets/icons/amazon.svg'),
  },
  {
    sheetName: '$GOOG',
    companyName: 'Google',
    revenueQuarter: 1,
    revenueRow: 5,
    netIncomeRow: 41,
    grossMarginRow: 25,
    icon: require('@/assets/icons/google.svg'),
  },
  // {
  //   sheetName: '$META',
  //   companyName: 'Meta',
  //   revenueRow: 5,
  //   netIncomeRow: 27,
  //   grossMarginRow: 11,
  //   icon: require('@/assets/icons/meta.svg'),
  // },
  // {
  //   sheetName: '$MSFT',
  //   companyName: 'Microsoft',
  //   revenueRow: 9,
  //   netIncomeRow: 30,
  //   grossMarginRow: 15,
  //   icon: require('@/assets/icons/microsoft.svg'),
  // },
  // {
  //   sheetName: '$NVDA',
  //   companyName: 'Nvidia',
  //   revenueRow: 5,
  //   netIncomeRow: 29,
  //   grossMarginRow: 11,
  //   icon: require('@/assets/icons/nvidia.svg'),
  // },
  // {
  //   sheetName: '$TSLA',
  //   companyName: 'Tesla',
  //   revenueRow: 13,
  //   netIncomeRow: 44,
  //   grossMarginRow: 26,
  //   icon: require('@/assets/icons/tesla.svg'),
  // },
];

export const colorArray = [
  '#39DAFF',
  '#31BFE2',
  '#29A5C5',
  '#218AA8',
  '#196F8C',
  '#11546F',
  '#093A52',
];
